
title: GEEDEVS Nairobi Community
page-top-title: GEEDEVS Nairobi Community
<<<<<<< HEAD
top-section-bg-text: Computer Science
=======
top-section-bg-text: Geospatial Data Science
>>>>>>> origin/fix
home-subtitle: About GEEDEVS Nairobi Community
